// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcLpzS2Vw1jXCFU4cMqRWBfp0anHCRDKM',
    appId: '1:839056540941:web:8989ba10db4a7d8d5d9c44',
    messagingSenderId: '839056540941',
    projectId: 'advance-flutter-exam-4eb8a',
    authDomain: 'advance-flutter-exam-4eb8a.firebaseapp.com',
    storageBucket: 'advance-flutter-exam-4eb8a.appspot.com',
    measurementId: 'G-MJ4BYX6KDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3p4J9PABRVe4yjk3nBrhyTw1Gq46ykDo',
    appId: '1:839056540941:android:21d3b8e62499494d5d9c44',
    messagingSenderId: '839056540941',
    projectId: 'advance-flutter-exam-4eb8a',
    storageBucket: 'advance-flutter-exam-4eb8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJmvfU6l21Br-UgYbcxkO7ZJwz7MrCB2I',
    appId: '1:839056540941:ios:c9b7167ecf2dfa4c5d9c44',
    messagingSenderId: '839056540941',
    projectId: 'advance-flutter-exam-4eb8a',
    storageBucket: 'advance-flutter-exam-4eb8a.appspot.com',
    iosBundleId: 'com.example.afExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJmvfU6l21Br-UgYbcxkO7ZJwz7MrCB2I',
    appId: '1:839056540941:ios:c9b7167ecf2dfa4c5d9c44',
    messagingSenderId: '839056540941',
    projectId: 'advance-flutter-exam-4eb8a',
    storageBucket: 'advance-flutter-exam-4eb8a.appspot.com',
    iosBundleId: 'com.example.afExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcLpzS2Vw1jXCFU4cMqRWBfp0anHCRDKM',
    appId: '1:839056540941:web:326e80bfb1684b5a5d9c44',
    messagingSenderId: '839056540941',
    projectId: 'advance-flutter-exam-4eb8a',
    authDomain: 'advance-flutter-exam-4eb8a.firebaseapp.com',
    storageBucket: 'advance-flutter-exam-4eb8a.appspot.com',
    measurementId: 'G-3GRCDNEQJW',
  );
}
